# Generated by Django 4.1.5 on 2023-01-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_alter_category_options_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Dotacja', 'verbose_name_plural': 'Dotacje'},
        ),
    ]
