# Generated by Django 4.1.5 on 2023-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0007_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='odebrano?'),
        ),
    ]
